### ISSUE TITLE
README has wrong path to starter site

### ISSUE THREAD

**Issue by simonswiss** [hb-gatsby/gatsby-starter-lumen#2]
Hi, 

Looking super good!! 

FYI the README info shows a wrong / broken path to the star theme ( gatsby new Lumen `https://github.com/gatsbylabs/gatsby-starter-lumen` )

I think it should be `https://github.com/hb-gatsby/gatsby-starter-lumen` instead?

**Comment by wpioneer** [comment]
Thank you, I fix this
