### ISSUE TITLE
Statinamic port of this theme

### ISSUE THREAD

**Issue by thangngoc89** [hb-gatsby/gatsby-starter-lumen#3]
Hey. First of all, thanks for the awesome theme. I ported your theme to [Statinamic](https://github.com/MoOx/statinamic)  (another static site generator based on React and webpack).

Demo: https://khoanguyen.me/statinamic-theme-lumen/
Repo: https://github.com/thangngoc89/statinamic-theme-lumen

I tried to keep everything as close as possible with the original theme (along with best practice with React and Statinamic)

**Comment by wpioneer** [comment]
This is great, I added to readme =)

**Comment by thangngoc89** [comment]
Thanks you :+1:
